//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMetaApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        public CheckList()
        {
            this.CheckListItems = new HashSet<CheckListItem>();
        }
    
        public long Id { get; set; }
        public string CheckListName { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual ICollection<CheckListItem> CheckListItems { get; set; }
    }
}
