//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMetaApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListItem
    {
        public long Id { get; set; }
        public long CheckListId { get; set; }
        public string ItemText { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual CheckList CheckList { get; set; }
    }
}
